###################
## Docs          ##
## mkdocs config ##
###################
---
site_name: ES-Progress Bash Library
site_url: https://shell.es-progress.hu
site_author: Sandor Semsey
copyright: |
  <a href="#__consent">Change cookie settings</a><br>
  Copyright © 2021 Sandor Semsey
repo_url: https://github.com/es-progress/shell
repo_name: es-progress/shell
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/theme
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: en
  favicon: terminal.png
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - pymdownx.tasklist:
      clickable_checkbox: yes
  - pymdownx.mark
  - pymdownx.details
  - attr_list

plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
        reduce_boolean_attributes: true
  - literate-nav:
      nav_file: nav.md
  - git-revision-date-localized

extra:
  consent:
    title: Cookie consent
    description: |
      We use cookies to enhance your browsing experience and to measure the effectiveness of our documentation.<br>
      With your consent, you're helping us to make it better!
    actions:
      - manage
      - accept
  analytics:
    provider: google
    property: G-TDE6GG4EQV
