#!/bin/bash

TIMEFORMAT=%R

echo rounds,time
j=512
#for j in 16 32 64 100 128 150 192 256; do
  for i in {1..10}; do
    ssh-keygen -qa $j -t ed25519 -f test -N test
    echo $j,`(time ssh-keygen -qa $j -N tost -pP test -f test) 2>&1 >/dev/null`
    rm test{.pub,}
  done
#done
