#!/usr/bin/env bash
###################################################
## proxy                                         ##
##                                               ##
## Manage SOCKS5 proxy                           ##
##                                               ##
## Copyright 2020                                ##
## Sandor Semsey <semseysandor@gmail.com>        ##
## All rights reserved.                          ##
##                                               ##
## This work is published under the MIT License. ##
## https://choosealicense.com/licenses/mit/      ##
###################################################

##########
# CONFIG #
##########

# Arguments to SSH
#
# -f: go to background
# -q: quiet mode
# -N: don't execute commands (only port forwarding)
ssh_args="-fqN"

#############
# FUNCTIONS #
#############

# Usage
usage() {
  echo "Usage: proxy ACTION TARGET PORT"
  echo "Type 'proxy -h' for help"
  exit 1
}

# Version
version() {
  cat <<VERSION
proxy v0.8
Written by Sandor Semsey, Copyright(C) 2020
License MIT https://choosealicense.com/licenses/mit/
VERSION
  exit 0
}

# Help
show_help() {
  cat <<HELP
Usage: proxy ACTION TARGET PORT

Manage SOCKS5 tunnel

ACTIONS
open               Open tunnel
close              Close tunnel
status             Tunnel status

TARGET             Target string as you would give to ssh (USER@HOST)
PORT               Port number on local

OPTIONS
-v,--version       Print version information
-h, --help         Display this help

HELP
  exit 0
}

# Check if tunnel is open
check_tunnel_open() {
  if pgrep -f "${ssh_command}" >/dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

###########
# OPTIONS #
###########

# Parse options
###############

action="${1}"
target="${2}"
port="${3}"

# Validate options
##################

# Action
if [[ -z "${action}" ]]; then
  echo "Action missing"
  usage
fi

case "${action}" in
  open | close | status) ;;
  -v | --version)
    version
    ;;
  -h | --help)
    show_help
    ;;
  *)
    echo "Invalid action"
    usage
    ;;
esac

# Target
if [[ -z "${target}" ]]; then
  echo "Target missing"
  usage
fi
target="${1}"

# Port
if [[ -z "${port}" ]]; then
  echo "Port missing"
  usage
fi

################
# SCRIPT START #
################

# Exit on error
set -e

# Assemble SSH command
ssh_command="ssh ${ssh_args} -D ${port} ${target}"

# Switch action
case ${action} in
  open)
    # Open tunnel
    #############
    if check_tunnel_open; then
      echo "Tunnel already opened."
    else
      ${ssh_command}
      if ! check_tunnel_open; then
        echo "Tunnel could not be opened."
        exit 1
      fi
    fi
    ;;

  close)
    # Close tunnel
    ##############
    if check_tunnel_open; then
      pkill -f "${ssh_command}"
      if check_tunnel_open; then
        echo "Tunnel could not be closed."
        exit 1
      fi
    else
      echo "Tunnel already closed."
    fi
    ;;

  status)
    # Tunnel status
    ###############

    if check_tunnel_open; then
      echo "Tunnel is open."
    else
      echo "Tunnel is closed."
    fi
    ;;

  *)
    exit 1
    ;;
esac

exit 0
