#!/usr/bin/env bash
###################################################
## Interactions                                  ##
## Functions Library                             ##
##                                               ##
## Copyright 2020                                ##
## Sandor Semsey <semseysandor@gmail.com>        ##
## All rights reserved.                          ##
##                                               ##
## This work is published under the MIT License. ##
## https://choosealicense.com/licenses/mit/      ##
###################################################

# Ask for confirmation
#
# @param  $1  If there is any argument won't exit just return 1
###############################################################
confirm() {
  read -r -p "Are you sure? (y/n) "
  if [[ ${REPLY} != 'y' && ${REPLY} != 'Y' ]]; then
    [[ -z "${1}" ]] && abort
    return 1
  fi
  return 0
}

# Clear console screen
######################
cls() {
  printf "\033c"
}
