name: Docs
on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
jobs:
  format:
    name: Check format
    runs-on: ubuntu-20.04
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Install npm v8
        run: npm i -g npm@8

      - name: Check code-style
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check **/*.{md,yml}
  deploy:
    name: Deploy docs to gh-pages
    runs-on: ubuntu-20.04
    needs: format
    steps:
      - name: Self check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install mkdocs mkdocs-git-revision-date-localized-plugin mkdocs-literate-nav mkdocs-material mkdocs-minify-plugin

      - name: Deploy docs
        run: mkdocs gh-deploy --force
