name: Docs
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - "docs/**"
      - mkdocs.yml
jobs:
  format:
    name: Check format
    uses: es-progress/.github/.github/workflows/prettier.yml@main
    with:
      pattern: "**/*.{md,yml}"
  deploy:
    name: Deploy docs
    uses: es-progress/.github/.github/workflows/mkdocs.yml@main
    needs: format
