name: Docs
on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
jobs:
  format:
    name: Check format
    uses: ./.github/workflows/reuse-prettier.yml
    with:
      pattern: "**/*.{md,yml}"
  deploy:
    name: Deploy docs
    uses: ./.github/workflows/reuse-mkdocs.yml
    needs: format
