name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - .shellcheckrc
      - "bin/**"
      - "lib/**"
jobs:
  format:
    name: Check format
    uses: es-progress/.github/.github/workflows/beautysh.yml@main
  linter:
    name: Linting
    needs: format
    uses: es-progress/.github/.github/workflows/shellcheck.yml@main
