name: CI
on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'bin/**'
    #   - 'lib/**'
jobs:
  code-style:
    name: Check code style (beautysh)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # - name: Run beautysh
      #   uses: illvart/beautysh-action@latest
      #   with:
      #     args: '--force-function-style paronly --check bin/* lib/*'
