name: Deploy mkdocs
on:
  workflow_call:
jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-20.04
    steps:
      - name: Self check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: |
          pip install \
            mkdocs \
            mkdocs-literate-nav \
            mkdocs-material mkdocs-minify-plugin \
            mkdocs-git-revision-date-localized-plugin

      - name: Deploy docs
        run: mkdocs gh-deploy --force
