name: Check formatting (prettier)
on:
  workflow_call:
    inputs:
      pattern:
        description: File/dir/glob to check
        type: string
        required: true
jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Check code-style
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check ${{ inputs.pattern }}
