name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
      - "lib/**"
jobs:
  format:
    name: Check format
    uses: ./.github/workflows/reuse-beautysh.yml
    with:
      dir: bin/ lib/
  linter:
    name: Linting
    needs: format
    uses: ./.github/workflows/reuse-shellcheck.yml
    with:
      dir: bin/ lib/
